"""Add foreign key indexes

Revision ID: 13c4688b573c
Revises: 3e8fc6206ae9
Create Date: 2026-07-20 23:59:59.153950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c4688b573c'
down_revision: Union[str, Sequence[str], None] = '3e8fc6206ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookmarks_content_id'), 'bookmarks', ['content_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_index(op.f('ix_content_topic_id'), 'content', ['topic_id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_exam_readiness_user_id'), 'exam_readiness', ['user_id'], unique=False)
    op.create_index(op.f('ix_learning_logs_topic_id'), 'learning_logs', ['topic_id'], unique=False)
    op.create_index(op.f('ix_learning_logs_user_id'), 'learning_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_notes_topic_id'), 'notes', ['topic_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_performance_records_topic_id'), 'performance_records', ['topic_id'], unique=False)
    op.create_index(op.f('ix_performance_records_user_id'), 'performance_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_prediction_history_topic_id'), 'prediction_history', ['topic_id'], unique=False)
    op.create_index(op.f('ix_prediction_history_user_id'), 'prediction_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_question_bank_topic_id'), 'question_bank', ['topic_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_topic_id'), 'quiz_attempts', ['topic_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_content_id'), 'recommendation_feedback', ['content_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_user_id'), 'recommendation_feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendations_topic_id'), 'recommendations', ['topic_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_topic_performance_topic_id'), 'topic_performance', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_performance_user_id'), 'topic_performance', ['user_id'], unique=False)
    op.create_index(op.f('ix_weak_topics_topic_id'), 'weak_topics', ['topic_id'], unique=False)
    op.create_index(op.f('ix_weak_topics_user_id'), 'weak_topics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weak_topics_user_id'), table_name='weak_topics')
    op.drop_index(op.f('ix_weak_topics_topic_id'), table_name='weak_topics')
    op.drop_index(op.f('ix_topic_performance_user_id'), table_name='topic_performance')
    op.drop_index(op.f('ix_topic_performance_topic_id'), table_name='topic_performance')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_topic_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendation_feedback_user_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_feedback_content_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_topic_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_question_bank_topic_id'), table_name='question_bank')
    op.drop_index(op.f('ix_prediction_history_user_id'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_topic_id'), table_name='prediction_history')
    op.drop_index(op.f('ix_performance_records_user_id'), table_name='performance_records')
    op.drop_index(op.f('ix_performance_records_topic_id'), table_name='performance_records')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_topic_id'), table_name='notes')
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_logs_user_id'), table_name='learning_logs')
    op.drop_index(op.f('ix_learning_logs_topic_id'), table_name='learning_logs')
    op.drop_index(op.f('ix_exam_readiness_user_id'), table_name='exam_readiness')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_content_topic_id'), table_name='content')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_content_id'), table_name='bookmarks')
    # ### end Alembic commands ###
