"""Add phase 1 features

Revision ID: 3e8fc6206ae9
Revises: f3d01f061ff8
Create Date: 2026-07-16 00:46:48.663917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8fc6206ae9'
down_revision: Union[str, Sequence[str], None] = 'f3d01f061ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('timestamp', sa.Float(), nullable=True))
    op.add_column('bookmarks', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'note')
    op.drop_column('bookmarks', 'timestamp')
    # ### end Alembic commands ###
