"""Initial schema

Revision ID: f4e85c664c7b
Revises: 
Create Date: 2026-07-15 23:34:33.427870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e85c664c7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invitation_tokens_token_key'), 'invitation_tokens', type_='unique')
    op.drop_index(op.f('ix_invitation_tokens_token'), table_name='invitation_tokens')
    op.create_index(op.f('ix_invitation_tokens_token'), 'invitation_tokens', ['token'], unique=True)
    op.drop_index(op.f('idx_learning_logs_user_id'), table_name='learning_logs')
    op.drop_index(op.f('idx_learning_sessions_user_id'), table_name='learning_sessions')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_index(op.f('idx_performance_records_user_topic'), table_name='performance_records')
    op.drop_index(op.f('idx_prediction_history_user_id'), table_name='prediction_history')
    op.drop_index(op.f('idx_quiz_attempts_timestamp'), table_name='quiz_attempts')
    op.drop_index(op.f('idx_quiz_attempts_topic_id'), table_name='quiz_attempts')
    op.drop_index(op.f('idx_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('idx_topic_performance_topic_id'), table_name='topic_performance')
    op.drop_index(op.f('idx_topic_performance_user_id'), table_name='topic_performance')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('idx_topic_performance_user_id'), 'topic_performance', ['user_id'], unique=False)
    op.create_index(op.f('idx_topic_performance_topic_id'), 'topic_performance', ['topic_id'], unique=False)
    op.create_index(op.f('idx_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_index(op.f('idx_quiz_attempts_topic_id'), 'quiz_attempts', ['topic_id'], unique=False)
    op.create_index(op.f('idx_quiz_attempts_timestamp'), 'quiz_attempts', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_prediction_history_user_id'), 'prediction_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_performance_records_user_topic'), 'performance_records', ['user_id', 'topic_id'], unique=False)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index(op.f('idx_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_learning_logs_user_id'), 'learning_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_invitation_tokens_token'), table_name='invitation_tokens')
    op.create_index(op.f('ix_invitation_tokens_token'), 'invitation_tokens', ['token'], unique=False)
    op.create_unique_constraint(op.f('invitation_tokens_token_key'), 'invitation_tokens', ['token'])
    # ### end Alembic commands ###
