import { useState, useEffect } from 'react'
import { Users, BookOpen, BrainCircuit, Activity, ArrowRight, Server, ShieldCheck } from 'lucide-react'
import api from '../../lib/api'

type AdminStats = any

export default function AdminDashboard() {
  const [stats, setStats] = useState<AdminStats | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchStats = async () => {
      try {
        const response = await api.get('/api/admin/stats')
        setStats(response.data.data)
      } catch (error) {
        console.error('Failed to fetch admin stats', error)
      } finally {
        setLoading(false)
      }
    }
    fetchStats()
  }, [])

  return (
    <div className="max-w-7xl mx-auto space-y-8 pb-12">
      <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-8">
        <div>
          <h1 className="text-3xl font-black text-white tracking-tight">Platform Overview</h1>
          <p className="text-slate-400 mt-2 font-medium">System health, metrics, and high-level analytics.</p>
        </div>
        <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-xl px-4 py-2 flex items-center gap-2">
          <ShieldCheck size={16} className="text-emerald-400" />
          <span className="text-sm font-bold text-emerald-400">All Systems Operational</span>
        </div>
      </header>

      {/* Primary Metrics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {[
          { label: 'Total Users', value: loading ? '...' : stats?.platform?.total_users, sub: `${loading ? '...' : stats?.platform?.active_users_today} active today`, icon: Users, color: 'text-blue-400', bg: 'bg-blue-500/10', border: 'border-blue-500/20' },
          { label: 'Total Content', value: loading ? '...' : (stats?.platform?.total_videos || 0) + (stats?.platform?.total_study_materials || 0), sub: 'Videos & Materials', icon: BookOpen, color: 'text-emerald-400', bg: 'bg-emerald-500/10', border: 'border-emerald-500/20' },
          { label: 'ML Predictions', value: loading ? '...' : stats?.ml?.total_predictions, sub: 'Generated by models', icon: BrainCircuit, color: 'text-rose-400', bg: 'bg-rose-500/10', border: 'border-rose-500/20' },
          { label: 'Quiz Attempts', value: loading ? '...' : stats?.platform?.total_quizzes, sub: 'Platform-wide', icon: Activity, color: 'text-amber-400', bg: 'bg-amber-500/10', border: 'border-amber-500/20' }
        ].map((stat, idx) => {
          const Icon = stat.icon
          return (
            <div key={idx} className={`bg-surface-800 border ${stat.border} rounded-3xl p-6 relative overflow-hidden group hover:border-white/20 transition-colors`}>
              <div className="flex justify-between items-start mb-4">
                <div className={`w-12 h-12 rounded-2xl ${stat.bg} ${stat.color} flex items-center justify-center shadow-lg group-hover:scale-110 transition-transform`}>
                  <Icon size={24} />
                </div>
              </div>
              <h3 className="text-3xl font-black text-white tracking-tight mb-1">{stat.value}</h3>
              <p className="text-sm font-bold text-slate-300 uppercase tracking-widest">{stat.label}</p>
              <p className="text-xs text-slate-500 mt-2 font-medium">{stat.sub}</p>
            </div>
          )
        })}
      </div>

      {/* Secondary Metrics */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* Knowledge Graph Status */}
        <div className="bg-surface-800 border border-white/[0.06] rounded-3xl p-8">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-purple-500/10 text-purple-400 flex items-center justify-center">
              <Server size={20} />
            </div>
            <h2 className="text-xl font-bold text-white">Knowledge Graph</h2>
          </div>
          
          <div className="grid grid-cols-2 gap-6">
            <div>
              <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Topics (Nodes)</p>
              <p className="text-3xl font-black text-white">{loading ? '...' : stats?.knowledge_graph?.topics}</p>
            </div>
            <div>
              <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Relationships (Edges)</p>
              <p className="text-3xl font-black text-white">{loading ? '...' : stats?.knowledge_graph?.relationships}</p>
            </div>
            <div>
              <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Model Status</p>
              <p className="text-sm font-bold text-emerald-400 bg-emerald-500/10 px-3 py-1.5 rounded-lg inline-block mt-1 uppercase">
                {loading ? '...' : stats?.ml?.status}
              </p>
            </div>
            <div>
              <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Total Questions</p>
              <p className="text-3xl font-black text-white">{loading ? '...' : stats?.platform?.total_questions}</p>
            </div>
          </div>
        </div>

        {/* System Logs / Activity Stub */}
        <div className="bg-surface-800 border border-white/[0.06] rounded-3xl p-8 flex flex-col">
          <h2 className="text-xl font-bold text-white mb-6">Recent Platform Activity</h2>
          
          <div className="flex-1 space-y-4">
            {[
              { text: 'New instructor account created', time: '5m ago', type: 'user' },
              { text: 'System backup completed successfully', time: '1h ago', type: 'system' },
              { text: 'Large video upload finished (Course: DSA)', time: '2h ago', type: 'content' },
              { text: 'Spam filter flagged 3 comments', time: '5h ago', type: 'security' },
            ].map((log, i) => (
              <div key={i} className="flex items-center gap-4 p-3 rounded-xl hover:bg-white/[0.02] transition-colors border border-transparent hover:border-white/5">
                <div className="w-2 h-2 rounded-full bg-slate-500 shrink-0" />
                <p className="text-sm text-slate-300 flex-1">{log.text}</p>
                <span className="text-xs font-medium text-slate-500">{log.time}</span>
              </div>
            ))}
          </div>

          <button className="w-full mt-4 py-3 rounded-xl bg-surface-900 hover:bg-surface-700 text-slate-300 font-bold transition-colors text-sm flex items-center justify-center gap-2 group border border-white/5">
            View All Logs
            <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" />
          </button>
        </div>
      </div>
    </div>
  )
}
